name: saltstack-skeleton-formula
source: https://github.com/bechtoldt/saltstack-skeleton-formula
summary: SaltStack formula skeleton that can be used for new formulas
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
extra:
  asciinema:
    link: https://asciinema.org/a/18108
